<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap — DROPYMART</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #f3f5f8;
            background: #0b1e36;
            padding: 2rem;
            margin: 0;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: rgba(11, 30, 54, 0.85);
            padding: 2.5rem;
            border-radius: 16px;
            border: 1px solid rgba(255, 255, 255, 0.08);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
            backdrop-filter: blur(8px);
          }
          h1 {
            color: #fbc02d;
            margin-top: 0;
            font-size: 2rem;
            font-weight: 700;
          }
          p {
            color: #a0aec0;
            line-height: 1.6;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 2rem;
          }
          th, td {
            text-align: left;
            padding: 1rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.08);
          }
          th {
            background: rgba(251, 192, 45, 0.1);
            color: #fbc02d;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.85rem;
            letter-spacing: 0.05em;
          }
          td {
            font-size: 0.9rem;
          }
          tr:hover td {
            background: rgba(255, 255, 255, 0.02);
          }
          a {
            color: #fbc02d;
            text-decoration: none;
            transition: color 0.2s ease;
          }
          a:hover {
            color: #f9a825;
            text-decoration: underline;
          }
          .footer {
            margin-top: 2.5rem;
            font-size: 0.8rem;
            color: #718096;
            text-align: center;
            border-top: 1px solid rgba(255, 255, 255, 0.08);
            padding-top: 1.5rem;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>XML Sitemap</h1>
          <p>This is a dynamically generated XML Sitemap for search engines (Google, Bing, Brave). You can read more about XML sitemaps at <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
          <table>
            <thead>
              <tr>
                <th>Location / URL</th>
                <th>Priority</th>
                <th>Change Frequency</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="//*[local-name()='url']">
                <tr>
                  <td>
                    <a href="{*[local-name()='loc']}">
                      <xsl:value-of select="*[local-name()='loc']"/>
                    </a>
                  </td>
                  <td><xsl:value-of select="*[local-name()='priority']"/></td>
                  <td><xsl:value-of select="*[local-name()='changefreq']"/></td>
                  <td><xsl:value-of select="*[local-name()='lastmod']"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          <div class="footer">
            Generated by DROPYMART Sitemap Generator Engine
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
